services:
  app:
    build:
      context: .
      target: runtime
    ports:
      - "4321:4321"
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:4321/health || exit 1"]
    #   interval: 30s
    #   timeout: 10s
    #   start_period: 5s
    #   retries: 3
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=production
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_BUCKET_REGION=${AWS_BUCKET_REGION}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_S3_URL=${AWS_S3_URL}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - VAPID_SUBJECT=${VAPID_SUBJECT}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
      - PUBLIC_VAPID_PUBLIC_KEY=${PUBLIC_VAPID_PUBLIC_KEY}
    restart: unless-stopped
    networks:
      - tutly_network

networks:
  tutly_network:
    driver: bridge
