services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tutly_local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tutly_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - LOCALSTACK_HOST=localhost
      - USE_SSL=0
      - PERSISTENCE=1
      - DATA_DIR=/var/lib/localstack
      - DISABLE_CORS_CHECKS=1
      - DEBUG=1
    volumes:
      - ./data/localstack:/var/lib/localstack
    networks:
      - tutly_network
    healthcheck:
      test: ["CMD-SHELL", "awslocal s3 ls"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  postgres_data:

networks:
  tutly_network:
    driver: bridge
