services:
  app:
    build:
      context: .
      target: runtime
    ports:
      - "4321:4321"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tutly_local
      - NODE_ENV=development
      - HOST=0.0.0.0
      - HOSTNAME=0.0.0.0
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - tutly_network
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:4321/health || exit 1"]
    #   interval: 30s
    #   timeout: 10s
    #   start_period: 5s
    #   retries: 3

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tutly_local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U postgres"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
    networks:
      - tutly_network

volumes:
  postgres_data:

networks:
  tutly_network:
    driver: bridge
