services:
  app:
    build:
      context: .
      target: runtime
    ports:
      - "4321:4321"
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:4321/health || exit 1"]
    #   interval: 30s
    #   timeout: 10s
    #   start_period: 5s
    #   retries: 3
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=production
      - RESEND_API_KEY=${RESEND_API_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - AUTH_TRUST_HOST=${AUTH_TRUST_HOST}
      - AUTH_SECRET=${AUTH_SECRET}
      - VAPID_SUBJECT=${VAPID_SUBJECT}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
      - PUBLIC_VAPID_PUBLIC_KEY=${PUBLIC_VAPID_PUBLIC_KEY}
    restart: unless-stopped
    networks:
      - tutly_network

networks:
  tutly_network:
    driver: bridge
