name = "tutly"
compatibility_date = "2024-02-03"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = "dist"

[vars]
NODE_ENV = "production"

[env.preview.vars]
NODE_ENV = "development"

[[kv_namespaces]]
binding = "TUTLY_KV"
id = "619a0a1a69af46d483b55b5d6d1cf25c"
preview_id = "9929b888aa004b46aa7a99318a162179" 