name: "Code Quality"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  format-lint:
    name: "Format and Lint"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup Node.js"
        uses: "actions/setup-node@v4"
        with:
          node-version: "latest"

      - name: "Install dependencies"
        run: "npm install --legacy-peer-deps"

      - name: "Check formatting"
        run: "npm run format:check"

      - name: "Check ESLint"
        run: "npm run lint"
